# Notebook 1 : Intro to Data and Data Visualization


---


In general, I have found programming to be similar to casting a spell in Harry Potter. Knowing the right spell can get Harry out of a Dementor's grasp. Meanwhile, knowing a what function/library to use can save you time (and your program's runtime).



---



## Learning objectives
- Load data into a Colab
- Clean data
  - Removing duplicates
  - Removing columns
  - Removing NaN's
- Visualize data with:
  - Histograms
  - Time series plots
  - Scatter plots

## Libraries:

In [ ]:
#Libraries

#Organize and Load data
import pandas as pd

#Visualize Data (quickly)
import plotly.express as px

#Layer Visualizations
import plotly.graph_objects as go

## Data Sets

- MNIST
- Microsoft (MSFT) Stock
- [Customer Call List](https://github.com/AlexTheAnalyst/PandasYouTubeSeries/blob/main/Customer%20Call%20List.xlsx)

# 1. Importing data

In practice, you will normally import data from a file given to you.

Hence, importing data typically require two things.
1. You know the command to load in the data
2. You know both the file path and filename.

Then, if you continue to use google colab for your projects. You can give access google colab access to your google drive, and load files through google drive. Although we will not be utilizing this here. The code for mounting your google drive is below.

In [ ]:
# Code for "mounting" (giving google colab access to) google drive
# We will not be using this, but is good to know
#from google.colab import drive
#drive.mount('/content/drive')

Once you have access to data through a CSV or an excel file, to load in data from either file types, we will use the following pandas functions:


> pd.read_csv('/filepath/file_name.csv')



> pd.read_excel('/filepath/file_name.xlsx')

We will then associate each of these sets of data with a data frame ( in code we denote "df" ).

## Example 1.1 -- Loading in data from a file path ( MNIST )

In [ ]:
#Loading data from filepath.
df_mnist = pd.read_csv('/content/sample_data/mnist_test.csv')

# Confidence Check : Look at the data
df_mnist

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Example 1.2 -- Loading data from a python package.

For a python package, the syntax for parameters may change based on the use case. Reference their documentation to be able to download a particular set of data.

In [ ]:
import yfinance as yf
import datetime

# 1. Define time frame for the stock data
start = datetime.datetime(2025, 1, 1)
end = datetime.datetime(2026, 4, 9)

# 2. Fetch data
# This returns the exact same Pandas DataFrame format
df_MSFT = yf.download('MSFT', start=start, end=end)

# Confidence Check : Look at the data
df_MSFT

/tmp/ipykernel_15382/3407125679.py:10: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            MSFT        MSFT        MSFT        MSFT      MSFT
Date
2025-01-02  414.568604  421.986845  410.874369  421.452012  16896500
2025-01-03  419.292877  419.966353  415.519392  417.044612  16662900
2025-01-06  423.749756  430.157753  421.402473  423.898312  20573600
2025-01-07  418.322296  426.522945  416.767335  424.888764  18139100
2025-01-08  420.491272  422.878180  417.500225  419.401808  15054600
...                ...         ...         ...         ...       ...
2026-04-01  369.369995  373.989990  368.200012  373.489990  29417200
2026-04-02  373.459991  373.640015  364.149994  367.209991  24099100
2026-04-06  372.880005  373.730011  369.500000  373.489990  16146600
2026-04-07  372.290009  372.450012  366.559998  370.339996  21443300
2026-04-08  374.329987  385.000000  371.410004  384.980011  33009400

[316 rows x 5 columns]

In other cases, you may also load data in from github, or in some instances from a python package.

In the case of github.
1. Go to the file in github.
2. At the top right you will see a "raw" button, right click and copy the link.
3. The copied link is now your parameter for our function "pd.read_foo()" to read either a CSV or Excel file.

## Example 1.3 -- Loading data from github ( Caller data )

In [ ]:
#Loading in the data for
url = 'https://github.com/AlexTheAnalyst/PandasYouTubeSeries/raw/refs/heads/main/Customer%20Call%20List.xlsx'
df_call_list = pd.read_excel(url)

df_call_list

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# 2. Cleaning Data

When dealing with sets of data, whether it come from a survey you took, or from an online resource it may not have formatting you would like. Or, it may have information you do not care about. Our goal in this note book will be to touch on the basics of cleaning data

- Removing duplicates
- Removing NaN's (Filling them in with a blank string)
- Removing columns

The basic commands will be



> df_foo.drop_duplicates()

> df_foo.fillna("")

> df_foo.drop(columns = "COLUMN_NAME")

## Example 2.1 -- Caller data

In this example we will examine sample caller data (See [1] in Resources). What are things we notice about the data below?

In [ ]:
df_call_list

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

Notice that this set of data has duplicates, NaN's, a useless column, and inconsistent formatting. For the sake of time, we will only worry about duplicates, NaN's, and the useless column. However [1] covers how to clean all of these cases.

We will first
1. Remove Duplicates
2. Repalces NaN's with empty strings
3. Remove Columns we do not need

In [ ]:
# Saving the unclean call list to compare later
df_call_list_old = df_call_list

# Removing Duplicates
df_call_list = df_call_list.drop_duplicates()

df_call_list

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
# Removing NaN's (Replacing the NaN's)
df_call_list = df_call_list.fillna("")

#Visualize call list
df_call_list

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
# Removing irrelevant columns
df_call_list = df_call_list.drop(columns= ["Not_Useful_Column","Last_Name","Phone_Number", "Address"])

#Visualize call list
df_call_list

    CustomerID First_Name Paying Customer Do_Not_Contact
0         1001      Frodo             Yes             No
1         1002       Abed              No            Yes
2         1003     Walter               N
3         1004     Dwight             Yes              Y
4         1005        Jon               Y             No
5         1006        Ron             Yes            Yes
6         1007       Jeff              No             No
7         1008   Sherlock               N             No
8         1009    Gandalf             Yes
9         1010      Peter             Yes             No
10        1011    Samwise             Yes             No
11        1012      Harry               Y
12        1013        Don             Yes              N
13        1014     Leslie             Yes             No
14        1015       Toby               N             No
15        1016        Ron              No              N
16        1017   Michael              Yes             No
17        1018      Clark               Y
18        1019      Creed             N/a            Yes
19        1020     Anakin             Yes              N

As an extra clean up for the next section, we can remove rows with empty answers, or "N/a" as an answer. Then, standardize the answers.

In [ ]:
# Make all the Yes -> Y
#              No -> N
# in "Paying Customer" Column
df_call_list["Paying Customer"] = df_call_list["Paying Customer"].str.replace('Yes',"Y")
df_call_list["Paying Customer"] = df_call_list["Paying Customer"].str.replace('No',"N")

# Make all the Yes -> Y
#              No -> N
# in "Do_Not_Contact" Column
df_call_list["Do_Not_Contact"] = df_call_list["Do_Not_Contact"].str.replace('Yes',"Y")
df_call_list["Do_Not_Contact"] = df_call_list["Do_Not_Contact"].str.replace('No',"N")

#Visualize call list
df_call_list

    CustomerID First_Name Paying Customer Do_Not_Contact
0         1001      Frodo               Y              N
1         1002       Abed               N              Y
2         1003     Walter               N
3         1004     Dwight               Y              Y
4         1005        Jon               Y              N
5         1006        Ron               Y              Y
6         1007       Jeff               N              N
7         1008   Sherlock               N              N
8         1009    Gandalf               Y
9         1010      Peter               Y              N
10        1011    Samwise               Y              N
11        1012      Harry               Y
12        1013        Don               Y              N
13        1014     Leslie               Y              N
14        1015       Toby               N              N
15        1016        Ron               N              N
16        1017   Michael                Y              N
17        1018      Clark               Y
18        1019      Creed             N/a              Y
19        1020     Anakin               Y              N

In [ ]:
#Filtering through the call_list and column "Paying customer" to check for an empty string
for x in df_call_list.index:
  if (df_call_list.loc[x, "Paying Customer"] == '') or (df_call_list.loc[x, "Do_Not_Contact"] == ''):
    df_call_list.drop(x, inplace=True)

#Filtering through the call_list and column "Paying customer" to check for an "N/a"
for x in df_call_list.index:
  if df_call_list.loc[x, "Paying Customer"] == 'N/a' or df_call_list.loc[x, "Do_Not_Contact"] == 'N/a':
    df_call_list.drop(x, inplace=True)

#Visualize call list
df_call_list

    CustomerID First_Name Paying Customer Do_Not_Contact
0         1001      Frodo               Y              N
1         1002       Abed               N              Y
3         1004     Dwight               Y              Y
4         1005        Jon               Y              N
5         1006        Ron               Y              Y
6         1007       Jeff               N              N
7         1008   Sherlock               N              N
9         1010      Peter               Y              N
10        1011    Samwise               Y              N
12        1013        Don               Y              N
13        1014     Leslie               Y              N
14        1015       Toby               N              N
15        1016        Ron               N              N
16        1017   Michael                Y              N
19        1020     Anakin               Y              N

# 3. Visualizations

In this section, we will explore three different ways to visualize data via: histograms, time-series, scatter  plots, and 3D scatter plots.

## Example 3.1 -- Histograms

For histograms, let's consider on our call list, how many customers do we already have paying for our services, compared to the number of people who are not. We will use the following function to visualize our call list data frame.  

> px.histogram(df_foo, x="columns")

In [ ]:
#Creating the bar chart/ histogram
fig_hist = px.bar(df_call_list, x="Paying Customer")

#Visualizing bar chart
fig_hist



### Histogram lab (LAB TIME!)
- Part a -- We saw in example 3.1 how to create a histogram. Now create a histogram with the "Do_Not_Contact" column.
- Part b -- Now use the the following fuction to overlay the two histograms

```python
fig = go.Figure()
fig.add_trace(go.Histogram(x=df['column_1']))
fig.add_trace(go.Histogram(x=df['column_2']))
fig.update_layout(barmode='group')
```

## Example 3.2 -- Time Series

In a time series, we want to visualize a measured value over time. In this partiuclar example we will visualize Microsoft stock close value every week.

> px.line(df_foo, x='Date', y='plot_vals')

In [ ]:
df_MSFT_plot = df_MSFT.reset_index()
# Flatten multi-level columns from yfinance output
df_MSFT_plot.columns = ['_'.join(col).strip() if isinstance(col, tuple) and col[1] else col[0] for col in df_MSFT_plot.columns.values]

#Notice this is tuple
print(df_MSFT.columns)

#Notice this is an arrary of names
print(df_MSFT_plot.columns)

#Creating time series line plot
fig_time_ser = px.line(df_MSFT_plot, x='Date', y='Close_MSFT')

#Visualizing time series chart
fig_time_ser

MultiIndex([( 'Close', 'MSFT'),
            (  'High', 'MSFT'),
            (   'Low', 'MSFT'),
            (  'Open', 'MSFT'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])
Index(['Date', 'Close_MSFT', 'High_MSFT', 'Low_MSFT', 'Open_MSFT',
       'Volume_MSFT'],
      dtype='object')

### Time-Series lab
- Part a -- Find the code (ticker symbol)  for any company's stock and create a Time-Series chart similar to example 3.2.
- Part b -- Now use the the following function to overlay the two time series visuals

```python
fig = go.Figure()
fig.add_trace(go.Scatter(x=df['column_1']))
fig.add_trace(go.Scatter(x=df['column_2']))
```

## Example 3.3 -- Scatter Plot

Scatter plots can be useful to recognize trends. Here will apply the following function

> px.scatter(x='x_vals', y='y_vals')

to visualize our Microsoft data again.

In [ ]:
fig_scatter = px.scatter(df_MSFT_plot, x='Date', y='Close_MSFT', title='MSFT Stock Price (Close) Scatter Plot')
fig_scatter

## Example 3.4 -- 3D Scatter Plot

In some instance, we want to compare and plot more than two values. The following function allows us to compare 3 seperate values visually.



> px.scatter_3d(df, x='col_1', y='col_2', z='col_3', color='col_4')

In [ ]:
fig = px.scatter_3d(df_MSFT_plot, x='Date', y='High_MSFT', z='Low_MSFT')
fig.show()



### 3D Visualization lab
- Part a -- Using the same stock you found in #2, create a 3D scatter plot for this new stock.
- Part b -- Now use the following function to overlay the two 3D scatter plots

```python
fig = go.Figure()
fig.add_trace(
    go.Scatter3d(
    x=df['column_1'],
    y=df['column_2'],
    z=['column_3'],
    mode='markers',
    name='Name of Chart'
    )
  )
```

# Resources

1. [Data Cleaning in Pandas | Python Pandas Tutorials ](https://www.youtube.com/watch?v=bDhvCp3_lYw) ( We used the sample data from this video )
2. [Ploty Historgrams](https://plotly.com/python/histograms/)
3. [Plotly Time-Series](https://plotly.com/python/time-series/)
4. [Scatter Plots](https://plotly.com/python/line-and-scatter/)